[package]
name = "gta-tools"
version = "0.4.2"
edition = "2024"

[dependencies]
catppuccin-egui = { version = "5.5.0", default-features = false, features = [
    "egui31",
] }
chrono = "0.4.40"
dirs = "6.0.0"
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["image", "svg"] }
image = { version = "0.25.6", default-features = false, features = ["png"] }
open = "5.3.2"
semver = "1.0.26"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = { version = "0.27.1", features = ["derive"] }
sysinfo = { git = "https://github.com/GuillaumeGomez/sysinfo", rev = "bcbb7b2b389b8800ff457773f48b130e710458fc" }
ureq = { version = "3.0.11", features = ["json"] }
windows = { version = "0.61.1", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Security",
    "Win32_NetworkManagement_WindowsFirewall",
] }
winreg = "0.55.0"

[build-dependencies]
static_vcruntime = "2.0.0"
winresource = "0.1.20"

[profile.release]
strip = true
lto = true
codegen-units = 1
