[package]
name = "gta-tools"
version = "0.1.2"
edition = "2024"

[dependencies]
catppuccin-egui = { version = "5.5.0", default-features = false, features = [
    "egui31",
] }
eframe = "0.31.1"
image = { version = "0.25.6", default-features = false }
open = "5.3.2"
sysinfo = "0.33.1"
windows = { version = "0.61.1", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
] }
winreg = "0.55.0"

[build-dependencies]
static_vcruntime = "2.0.0"
winresource = "0.1.20"

[profile.release]
strip = true
lto = true
codegen-units = 1
